#! /bin/sh
### BEGIN INIT INFO
# Provides:          Telegram_BOT
# Required-Start:    $domoticz.sh $network $remote_fs $syslog $
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A Telegram bot designed to control Domoticz
# Description:       domoticz2bot is the supporting Lua code to enable a Telegram bot to control your Domoticz system..
#                    This is an init script do make it a daemon.
#                    After creating a Telegram bot then in combination with this Lua code you can use it to send your system
#                    commands to execute via other Telegram apps (PC - Phone - Web or other) while not
#                    logged in to the system.
#
#                    Note #1: This version of the init script is developed for raspbian (rapberry PI port of Debian Wheezy).
#
#                    Note #2: All parameters are set from /etc/profile.d/DomoticzData.sh
#
#                    See: https://core.telegram.org/bots for more information.
### END INIT INFO

# Do NOT "set -e"

# Get the preset variables
. /etc/profile.d/DomoticzData.sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DESC="Telegram Bot for Domoticz"
NAME=dtgbot
USERNAME=pi
DAEMON=$BotHomePath$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Carry out specific functions when asked to by the system
case "$1" in

    start)
        echo -n "Starting $DESC ... "
        . /etc/profile.d/DomoticzData.sh && start-stop-daemon --start --background --make-pidfile $PIDFILE --pidfile $PIDFILE \
            --startas $DAEMON --name $NAME || true
        echo "Done."
    ;;

    stop)
        echo -n "Stopping $DESC ... "
        start-stop-daemon --stop --retry 2 --pidfile $PIDFILE \
            --name $NAME || true
        rm -f $PIDFILE
        sleep 2
        echo "Killing the running script 1."
        sudo pkill -SIGKILL -e -f dtgbot/dtgbot.lua >> /var/tmp/dtgrestart.log
        echo "Done."

    ;;
    restart)
        echo -n "Restarting $DESC "
        start-stop-daemon --stop --retry 2 --pidfile $PIDFILE \
            --name $NAME || true
        rm -f $PIDFILE
        sleep 2
		echo "Killing the running script 2."
        sudo pkill -SIGKILL -e -f dtgbot/dtgbot.lua >> /var/tmp/dtgrestart.log
        . /etc/profile.d/DomoticzData.sh && start-stop-daemon --start --background --make-pidfile $PIDFILE --pidfile $PIDFILE \
            --startas $DAEMON --name $NAME || true
        echo "Done."
    ;;

    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;

    *)
        N=/etc/init.d/$NAME
        echo "Usage $NAME: $SCRIPTNAME {start|stop|restart|status}"
        exit 1
    ;;

esac
